### ISSUE TITLE
Cross browser CSS differences

### ISSUE THREAD

**Issue by Abg4real** [kothariji/SyntaxMeets#10]
Hi
I checked out your project and the concept is really cool!
While I was trying the room feature I noticed that the font size section of the editor seems to be overlapping the right side section in my 14" laptop. (1366x768px).
![image](https://user-images.githubusercontent.com/55308761/100571645-a2880200-32f9-11eb-94b4-b4e0925f6995.png)

**Comment by kothariji** [comment]
@Abg4real  Thank you 🙏 👍 
We will definitely look forward to resolve the issue in the upcoming release.

**Comment by AmeyaJain-25** [comment]
Hi @kothariji ,
If allowed, can I take this issue or it's resolved
If this issue isn't resolved,
Please allow me to resolve this issue...

**Comment by kothariji** [comment]
> Hi @kothariji ,
> If allowed, can I take this issue or it's resolved
> If this issue isn't resolved,
> Please allow me to resolve this issue...

@AmeyaJain-25 
Please go ahead and resolve that issue. 
Just create a PR once done ..and don't forget to add comments so that it would be easy for others to understand 😉 .

**Comment by AmeyaJain-25** [comment]
Thanks

**Comment by AmeyaJain-25** [comment]
I wanted to confirm that is it's okay if I bring the input bars below the syntaxMeets logo.
It's responsive in all the tabs. 

When its width is greater than 1385px, then they will remain at the same place, and if it's less, then they will be coming down.

![image](https://user-images.githubusercontent.com/66305085/102691490-fc158980-4232-11eb-9d45-beb3a19de0c6.png)
![image](https://user-images.githubusercontent.com/66305085/102691489-fae45c80-4232-11eb-9523-71f227aba4b1.png)
![image](https://user-images.githubusercontent.com/66305085/102691486-f28c2180-4232-11eb-83fc-805e0c49b4f4.png)

**Comment by AmeyaJain-25** [comment]
Or, the input bars should be there in one row only..?

**Comment by kothariji** [comment]
@AmeyaJain-25 
I think that would work for now...later on, we can look deeper into that.
So I am assigning this issue to you.
Create a PR.

**Comment by AmeyaJain-25** [comment]
Made the PR #14

**Comment by kothariji** [comment]
Yes, I checked and it's working as expected. Issue fixed 🛠️.
