### ISSUE TITLE
Emoji Icon Alignment

### ISSUE THREAD

**Issue by jainaayush01** [kothariji/SyntaxMeets#103]
**Describe the bug**
Describe the issue that you're seeing clearly.

**To Reproduce**
Clear steps describing how to reproduce the issue.
1. Go to https://syntaxmeets.vercel.app/
2. Create a room
3. Click on the chatbox
4. See the error

**Expected result**
It should be aligned with the chatbox

**Actual result**
Not aligned

**Screenshots**
![image](https://user-images.githubusercontent.com/54480934/113866747-4e22f080-97cb-11eb-98fd-6a1e717943a6.png)

**Are you willing to contribute to this issue?** Yes

**Comment by kothariji** [comment]
@jainaayush01, first of all, thank you so much for taking out time to create this issue.

Yes, the emoji icon is misaligned. 
Please go forward to work on this issue. I am assigning this Issue to you 👍

**Comment by jainaayush01** [comment]
Okay 👍👍
