### ISSUE TITLE
The name of the Participant overflows if too big

### ISSUE THREAD

**Issue by AmeyaJain-25** [kothariji/SyntaxMeets#106]
**Describe the bug**
If a random user gives it's name as a long string without spaces, then it get's overflowed in the participants block.

**To Reproduce**
Clear steps describing how to reproduce the issue.
1. Go to Website.
2. Give a long name without any spaces.
3. Go to participants tab.

**Expected result**
It should be able to see full name rather than the text going outside.

**Actual result**
It got overflowed.

**Screenshots**

![Screenshot from 2021-04-09 13-08-05](https://user-images.githubusercontent.com/66305085/114146618-70d11880-9935-11eb-862b-47c58ab41496.png)
![Screenshot from 2021-04-09 13-07-44](https://user-images.githubusercontent.com/66305085/114146607-6e6ebe80-9935-11eb-9c14-d0b1819ba668.png)

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Additional context**
I would like to work on this issue under GSSOC 21'

**Comment by Vishv07** [comment]
I think our next milestone should be to centralize the CSS @kothariji what do you say?

**Comment by kothariji** [comment]
Hi @AmeyaJain-25 , First of all, thank you so much for taking out the time to create this issue. 🚀

Definitely🙌, Please go forward to work on this issue. I am assigning this Issue to you 👍

**Comment by kothariji** [comment]
> I think our next milestone should be to centralize the CSS @kothariji what do you say?

Yesss, even I feel the same. 😄
