### ISSUE TITLE
Converting alert to toast message

### ISSUE THREAD

**Issue by AmeyaJain-25** [kothariji/SyntaxMeets#109]
**Is your feature request related to a problem? Please describe.**
When we refresh the page, name get's undefined or empty and hence it gives an alert of enter your name.
So, instead of alert, we can use a toast message of showing the name not found.

![Screenshot from 2021-04-09 19-08-42](https://user-images.githubusercontent.com/66305085/114189334-b7d80180-9967-11eb-8615-22ab6ec75e2f.png)

**Describe the solution you'd like**
Changing the alert to toast message

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Describe alternatives you've considered**
If not toast message, then a beautified popup of alert ok. 

**Additional context**
I would like to work on this issue under GSSoC21.

Please confirm that should I replace the alert with toast message and go to home page or a coloured alert asking ok button and then go to home page.

**Comment by Nishant127** [comment]
Hi @AmeyaJain-25, First of all, thank you so much for taking out the time to create this issue.

Definitely 🙌, Please go forward to work on this issue. I am assigning this Issue to you 👍

And last but not least,
Keep Contributing 🙏🔥
