### ISSUE TITLE
Changing the Language tab to the extension of file uploaded.

### ISSUE THREAD

**Issue by AmeyaJain-25** [kothariji/SyntaxMeets#111]
**Is your feature request related to a problem? Please describe.**
If we upload a file of extension eg .py, then the code appears in the block but the language tab is not changed.

**Describe the solution you'd like**
I would like to change the language tab also once the code uploaded file is having the extension of that particular file.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Describe alternatives you've considered**
Creating a dictionary or array of languages and it's extensions to match the code file extension and language tab.

**Additional context**
I would like to work on this issue under GSSoC21

**Comment by Nishant127** [comment]
Hi @AmeyaJain-25, First of all, thank you so much for taking out the time to create this issue.

Definitely 🙌, Please go forward to work on this issue. I am assigning this Issue to you 👍

And last but not least,
Keep Contributing 🙏🔥
