### ISSUE TITLE
about page creator link to be cursor: pointer

### ISSUE THREAD

**Issue by jainaayush01** [kothariji/SyntaxMeets#113]
**Describe the bug**
about page creator link to cursor: pointer

**To Reproduce**
Clear steps describing how to reproduce the issue.
1. Go to about tab

Yes, I am willing to work on this issue

**Comment by Akash-Salvi** [comment]
Hi @jainaayush01, First of all, thank you so much for taking out the time to create this issue.

Definitely 🙌, Please go forward to work on this issue. I am assigning this Issue to you 👍

And last but not least,
Keep Contributing 🙏🔥
