### ISSUE TITLE
Bug: Two same messages from same person

### ISSUE THREAD

**Issue by jainaayush01** [kothariji/SyntaxMeets#114]
**Describe the bug**
Describe the issue that you're seeing clearly.

**To Reproduce**
Clear steps describing how to reproduce the issue.
1. Go to App
2. Create a room and join with more than 2 persons
3. Type message from them and see the error

This behavior is not observed until 2 persons are there but after more than 2 person this type of behaviour is seen

**Expected result**
One Message to be broadcasted

**Actual result**
Two same messages from same person

**Screenshots**
![image](https://user-images.githubusercontent.com/54480934/114270573-bfacaa00-9a2a-11eb-9fa5-0d9e9bcfca54.png)

![image](https://user-images.githubusercontent.com/54480934/114270578-c804e500-9a2a-11eb-9c40-7914f8de22b3.png)

![image](https://user-images.githubusercontent.com/54480934/114270584-ccc99900-9a2a-11eb-80f2-c1e226116db2.png)

![image](https://user-images.githubusercontent.com/54480934/114270588-d81cc480-9a2a-11eb-8f02-f8e7e52e9b92.png)

**Are you willing to contribute to this issue?** Yes but i will definitely need help to resolve this issue any help is appreciated

**Desktop (please complete the following information):**
Chrom Latest

**Comment by Vishv07** [comment]
@Nishant127 Would you like to investigate why this problem is occurring?

**Comment by jainaayush01** [comment]
@Vishv07 I tried this on the same browser so that may be a cause for this happening. And when i tried this on a different browser i didn't find such happenings.

**Comment by nishant23122000** [comment]
Hello @Vishv07 , @jainaayush01  the issue is listening to the event more than one times when the user reloads the page because the event trigger more than 2 times,
Please go through this problem statement,
https://stackoverflow.com/questions/52138337/socket-io-makes-multiple-connections-when-the-page-is-refreshed-node-js
