### ISSUE TITLE
Message from the person should be as shown as blue and from other person it should be shown as grey

### ISSUE THREAD

**Issue by jainaayush01** [kothariji/SyntaxMeets#115]
**Describe the bug**
Message from the person should be as shown as blue and from other person it should be shown as grey

**To Reproduce**
Clear steps describing how to reproduce the issue.
1. Go to Chat
2. Type messages

**Expected result**
Message from the person should be as shown as blue and from other person it should be shown as grey

**Actual result**
First Person is in blue others in grey

Yes i am willing to contribute

**Comment by kothariji** [comment]
@jainaayush01 I think its working the same way you mentioned. The messages from sender is in blue, and when received from others its in grey.

Can you please elaborate.

**Comment by jainaayush01** [comment]
I have shared some screenshots in issue #114 where you can see that on all the different tabs The first user to post comments is in blue and others are in grey. I haven't named each screen but if you will try to regenerate you will get the idea.

If you still aren't clear please let me know, i will generate more screenshots

**Comment by jainaayush01** [comment]
![image](https://user-images.githubusercontent.com/54480934/114303566-5d1be280-9aec-11eb-88d5-1c41768acd38.png)
See Two Different person but same kind of colors.

**Comment by kothariji** [comment]
@jainaayush01 actually this type of behavior is possible when you are working on the same browser because then local storage for all will be the same. So try with different browsers or incognito, and let me know if the issue still remains

**Comment by jainaayush01** [comment]
Okay, i understand now as I also don't see a way to fix this by code, and also it doesn't remain the same and also I think this also closes #114 because I tried this again, and not happening now.

**Comment by kothariji** [comment]
> Okay, i understand now as I also don't see a way to fix this by code, and also it doesn't remain the same and also I think this also closes #114 because I tried this again, and not happening now.

Yes exactly... So you can close the issues🙌
