### ISSUE TITLE
Error message Snackbar on uploading photos instead of code

### ISSUE THREAD

**Issue by AmeyaJain-25** [kothariji/SyntaxMeets#119]
**Describe the bug**
Alert is showing while there is an error of uploading photo instead of code file.
That's the reason the alert should be converted to Alert or Snackbar.

**To Reproduce**
Clear steps describing how to reproduce the issue.
1. Go to 'Room'
2. Click on 'Upload file'
3. Upload an 'Image'

**Expected result**
Snackbar should be opened.

**Actual result**
alert is shown.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Comment by Akash-Salvi** [comment]
Hi @AmeyaJain-25, First of all, thank you so much for taking out the time to create this issue.

Definitely 🙌, Please go forward to work on this issue. I am assigning this Issue to you 👍

And last but not least,
Keep Contributing 🙏🔥
