### ISSUE TITLE
Room only shows updated content after first change

### ISSUE THREAD

**Issue by rsilvr** [kothariji/SyntaxMeets#12]
Hello. Great project you have here!
Doing some testing with the app I found this minor issue: by the time an user enter a room, he always sees the default code in C++ in the editor, regardless if another user already made changes to it. Just after a new change is done, the code in the editor is updated for the second user.

![first_user](https://user-images.githubusercontent.com/5250902/101283179-a57e6900-37b7-11eb-8f9f-c484bc7c93dc.png)
![second_user](https://user-images.githubusercontent.com/5250902/101283183-aca57700-37b7-11eb-9e04-a3920f41ffe8.png)
![updated_code](https://user-images.githubusercontent.com/5250902/101283192-b29b5800-37b7-11eb-99e1-74cbf53acbe0.png)

**Comment by Shubham-Kumar-2000** [comment]
Can You assign me this under GSSOC 21?

I was thinking to do this by implementing redis.

**Comment by kothariji** [comment]
> Can You assign me this under GSSOC 21?
> 
> I was thinking to do this by implementing redis.
> @kothariji

Hi @Shubham-Kumar-2000 , First of all, thank you so much for taking out the time to work on this issue.

Definitely 🙌, Please go forward to work on this issue. I am assigning this Issue to you 👍

Though I am not much familiar with Redis, but would love to explore it, so try your best out 🙌 

And last but not least,
Keep Contributing 🙏🔥

**Comment by Shubham-Kumar-2000** [comment]
Solved and Added PR

I refrained to add a huge dependency such as redis and solved it using logic.

**Comment by kothariji** [comment]
Fixed 🚀
Thanks, @Shubham-Kumar-2000  for the contribution 🙌

Keep Contributing 🔥
