### ISSUE TITLE
Customization Of Scrollbar

### ISSUE THREAD

**Issue by ShubhamSj07** [kothariji/SyntaxMeets#121]
**Is your feature request related to a problem? Please describe.**
Default Scrollbar is not looking perfect with ui, i would like to modify it

Default
![Default](https://user-images.githubusercontent.com/56510414/114342921-6fdcf880-9b7a-11eb-8063-9c71e77e61f8.JPG)

Customized
![Customized](https://user-images.githubusercontent.com/56510414/114342929-753a4300-9b7a-11eb-8512-140c4158b918.JPG)

**Are you willing to contribute to this issue?** [Yes/No]
Yes

Please assign me this issue

**Comment by Vishv07** [comment]
Niceeee @ShubhamSj07

**Comment by Akash-Salvi** [comment]
It looks great 🔥

**Comment by Akash-Salvi** [comment]
Hey @ShubhamSj07, First of all, thank you so much for taking out the time to create this issue.

Definitely 🙌, Please go forward to work on this issue. I am assigning this Issue to you 👍

And last but not least,
Keep Contributing 🙏🔥
