### ISSUE TITLE
Readme file enhancement

### ISSUE THREAD

**Issue by anirudhsai20** [kothariji/SyntaxMeets#128]
The Readme file can be enhanced by adding a list of all the Open Source progarms in which this project was listed in.

**Comment by anirudhsai20** [comment]
Hi! Please assign this issue to me under GSSOC.

**Comment by kothariji** [comment]
Hi @anirudhsai20, as of now the project is listed under GSSOC only. So I don't think there is a need of adding a single entry as of now, but yes in future, when the project goes to various other competitions, we can think of adding it. 
Thanks
