### ISSUE TITLE
Footer buttons information

### ISSUE THREAD

**Issue by AmeyaJain-25** [kothariji/SyntaxMeets#129]
**Is your feature request related to a problem? Please describe.**
If a user enters the room, then he/she may not know the functionality of the footer buttons and which is not a good user experience.
![WhatsApp Image 2021-04-29 at 10 01 26 AM](https://user-images.githubusercontent.com/66305085/117923462-ae004000-b311-11eb-97e8-4fc2fd985734.jpeg)

**Describe the solution you'd like**
We can add tooltip or title on hovering the buttons so that it may know well the use of those buttons.

**Are you willing to contribute to this issue?** [Yes/No]
YES

**Additional context**
Please assign me this issue under GSSoC21'

**Comment by kothariji** [comment]
Hi @AmeyaJain-25, First of all, thank you so much for taking out the time to create this issue.

Definitely 🙌, Please go forward to work on this issue. I am assigning this Issue to you 👍

And last but not least,
Keep Contributing 🙏🔥
