### ISSUE TITLE
Diable empty messages

### ISSUE THREAD

**Issue by garvitgupta13** [kothariji/SyntaxMeets#131]
**Describe the bug**
Currently anyone can send empty messages in the chat box
**To Reproduce**
Clear steps describing how to reproduce the issue.

**Expected result**
What should happen?

**Actual result**
It should not send any empty messages

**Screenshots**
![image](https://user-images.githubusercontent.com/70805691/118240107-391b3a80-b4b8-11eb-9427-9f7c5ffc4791.png)

**Are you willing to contribute to this issue?** [Yes]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Akash-Salvi** [comment]
Hi @garvitgupta13, First of all, thank you so much for taking out the time to create this issue.

Definitely 🙌, Please go forward to work on this issue. I am assigning this Issue to you 👍

And last but not least,
Keep Contributing 🙏🔥

**Comment by garvitgupta13** [comment]
Hey @Akash-Salvi can you please let me know where can I get me `REACT_APP_ONLINE_JUDGE_API` key

**Comment by AyushShri** [comment]
> Hey @Akash-Salvi can you please let me know where can I get `REACT_APP_ONLINE_JUDGE_API` key

It's a Rapid Api online Judge. Here is the [API Ref](https://rapidapi.com/judge0-official/api/judge0-ce). You can register and get your credentials.
happy Contributing !

**Comment by garvitgupta13** [comment]
> > Hey @Akash-Salvi can you please let me know where can I get `REACT_APP_ONLINE_JUDGE_API` key
> 
> It's a Rapid Api online Judge. Here is the [API Ref](https://rapidapi.com/judge0-official/api/judge0-ce). You can register and get your credentials.
> happy Contributing !

Please review my PR
