### ISSUE TITLE
Fullscreen Mode

### ISSUE THREAD

**Issue by umbridge** [kothariji/SyntaxMeets#133]
**Describe the bug**
to exit fullscreen, there should be exitfullscreen icon

**To Reproduce**
Clear steps describing how to reproduce the issue.
1. Go to 'https://syntaxmeets.vercel.app'
2. Click on 'fullscreen icon in syntax editor'
3. Error : exitfullscreen icon not present

**Expected result**
![image](https://user-images.githubusercontent.com/44002678/118313706-c5594c00-b510-11eb-9aa5-dadf05c8cf06.png)

**Actual result**
![image](https://user-images.githubusercontent.com/44002678/118310134-d3589e00-b50b-11eb-89c6-f84f91b6e22e.png)

**Are you willing to contribute to this issue?** [Yes]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by AyushShri** [comment]
> **Describe the bug**
> to exit fullscreen, there should be exitfullscreen icon
> 
> **To Reproduce**
> Clear steps describing how to reproduce the issue.
> 
> 1. Go to 'https://syntaxmeets.vercel.app'
> 2. Click on 'fullscreen icon in syntax editor'
> 3. Error : exitfullscreen icon not present
> 
> **Expected result**
> ![image](https://user-images.githubusercontent.com/44002678/118313706-c5594c00-b510-11eb-9aa5-dadf05c8cf06.png)
> 
> **Actual result**
> ![image](https://user-images.githubusercontent.com/44002678/118310134-d3589e00-b50b-11eb-89c6-f84f91b6e22e.png)
> 
> **Are you willing to contribute to this issue?** [Yes]
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]

Hi @umbridge , First of all, thank you so much for taking out the time to work on this issue #133.
Definitely , Please go forward to work on this issue. I am assigning this Issue to you +1

Also Its really great that you noticed such a bit of a thing which deserves appreciation.
I think we can go forward with it @kothariji . Also @kothariji , you can review the issue!
Happy Contributing @umbridge !

**Comment by umbridge** [comment]
> > **Describe the bug**
> > to exit fullscreen, there should be exitfullscreen icon
> > **To Reproduce**
> > Clear steps describing how to reproduce the issue.
> > 
> > 1. Go to 'https://syntaxmeets.vercel.app'
> > 2. Click on 'fullscreen icon in syntax editor'
> > 3. Error : exitfullscreen icon not present
> > 
> > **Expected result**
> > ![image](https://user-images.githubusercontent.com/44002678/118313706-c5594c00-b510-11eb-9aa5-dadf05c8cf06.png)
> > **Actual result**
> > ![image](https://user-images.githubusercontent.com/44002678/118310134-d3589e00-b50b-11eb-89c6-f84f91b6e22e.png)
> > **Are you willing to contribute to this issue?** [Yes]
> > **Desktop (please complete the following information):**
> > 
> > * OS: [e.g. iOS]
> > * Browser [e.g. chrome, safari]
> > * Version [e.g. 22]
> > 
> > **Smartphone (please complete the following information):**
> > 
> > * Device: [e.g. iPhone6]
> > * OS: [e.g. iOS8.1]
> > * Browser [e.g. stock browser, safari]
> > * Version [e.g. 22]
> 
> Hi @umbridge , First of all, thank you so much for taking out the time to work on this issue #133.
> Definitely , Please go forward to work on this issue. I am assigning this Issue to you +1
> 
> Also Its really great that you noticed such a bit of a thing which deserves appreciation.
> I think we can go forward with it @kothariji . Also @kothariji , you can review the issue!
> Happy Contributing @umbridge !

**Comment by umbridge** [comment]
Thank you @AyushShri !!

**Comment by kothariji** [comment]
@AyushShri Yes definitely we can go forward with this issue, thanks for the take-up.

@umbridge I have assigned the issue to you, feel free to work on this issue 🚀

**Comment by umbridge** [comment]
Thank You @AyushShri  and @kothariji for giving me an opportunity to contribute in this project.
The issue is resolved and PR has been created. Please check and let me if any modifications required.

**Comment by kothariji** [comment]
Thank you so much 🙌 😊
