### ISSUE TITLE
Improving About us page

### ISSUE THREAD

**Issue by kumarishalini6** [kothariji/SyntaxMeets#134]
**Is your feature request related to a problem? Please describe.**
The about us page's card is too simple I want to add some shadow and hover effect, and also want to add some effects on social media icons
![SyntaxMeets - Personal - Microsoft​ Edge 5_15_2021 02_02_33 PM](https://user-images.githubusercontent.com/69043944/118354031-90032d00-b515-11eb-8d42-d9e38e43f8d2.png)

**Comment by kumarishalini6** [comment]
I want to work on this issue under GSSoC;21 , please assign issue to me.

**Comment by Akash-Salvi** [comment]
Hi @kumarishalini6, First of all, thank you so much for taking out the time to create this issue.

However, currently, we don't feel that there is a real need for changes to the about us page.

Thank you, sorry for the inconvenience caused 🙌

**Comment by kumarishalini6** [comment]
It's ok ,please close the issue

**Comment by kumarishalini6** [comment]
it's ok
