### ISSUE TITLE
Creators Card in About page not aligned

### ISSUE THREAD

**Issue by AmeyaJain-25** [kothariji/SyntaxMeets#138]
**Describe the bug**
The Cards in about page are too close and gets more disturbed if screen size shrinks.

**To Reproduce**
Clear steps describing how to reproduce the issue.
1. Go to 'Syntaxmeets'
2. Go inside the room
3. Click on About Us

**Expected result**
The cards should be aligned properly.

**Actual result**
The cards aren't aligned in small screen sizes

**Screenshots**
![WhatsApp Image 2021-05-29 at 11 42 09 AM](https://user-images.githubusercontent.com/66305085/120060915-17a17d80-c078-11eb-9a08-afecd392f1d5.jpeg)

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Additional context**
Please assign me this issue under GSSoC21'

**Comment by kothariji** [comment]
Sure, please go ahead @AmeyaJain-25, I am assigning this issue to you
