### ISSUE TITLE
Notification message for new messages

### ISSUE THREAD

**Issue by AmeyaJain-25** [kothariji/SyntaxMeets#139]
**Is your feature request related to a problem? Please describe.**
When user messages in the chat. The other should know that message has arrived. So, this feature can be added.

**Describe the solution you'd like**
Showing a notification type message

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Comment by Akash-Salvi** [comment]
Sure, please go ahead @AmeyaJain-25, I am assigning this issue to you
