### ISSUE TITLE
About Us launches from differently

### ISSUE THREAD

**Issue by AmeyaJain-25** [kothariji/SyntaxMeets#140]
**Is your feature request related to a problem? Please describe.**
The Navbar About Us launches a Modal while the one from the footer launches it to another page.

**Describe the solution you'd like**
Make all in to the modal

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Comment by Akash-Salvi** [comment]
Sure, please go ahead @AmeyaJain-25, I am assigning this issue to you
