### ISSUE TITLE
Back/Close Button to the About Us

### ISSUE THREAD

**Issue by AmeyaJain-25** [kothariji/SyntaxMeets#141]
**Is your feature request related to a problem? Please describe.**
There is no Back/Close button to the about us modal

**Describe the solution you'd like**
Add a Back/Close button somewhat like this.
![WhatsApp Image 2021-05-29 at 2 37 02 PM](https://user-images.githubusercontent.com/66305085/120068967-f1dc9e80-c0a0-11eb-984b-8a4bd8ee5c3f.jpeg)

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Comment by Akash-Salvi** [comment]
Sure, please go ahead @AmeyaJain-25 , I am assigning this issue to you
