### ISSUE TITLE
Room Id text and button gets shrinked and disturbs the navbar

### ISSUE THREAD

**Issue by AmeyaJain-25** [kothariji/SyntaxMeets#142]
**Describe the bug**
The Copy room id button is not looking good in small screen sizes. In sizes less than 1060px

**To Reproduce**
Clear steps describing how to reproduce the issue.
1. Go to 'Syntax Room'
2. Reduce the screen size less than 1060px
3. See error

**Expected result**
It should either decrease it's size or else it can wrap the text and show 3 dots(Eg: RoomId: asq....), so that it will not affect the navbar UI

**Actual result**
It doesn't fit in the navbar properly

**Screenshots**
![Screenshot from 2021-05-29 12-05-34](https://user-images.githubusercontent.com/66305085/120069092-b393af00-c0a1-11eb-9f6f-6f9d59c92a81.png)

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Comment by Akash-Salvi** [comment]
Sure, please go ahead @AmeyaJain-25 , I am assigning this issue to you
