### ISSUE TITLE
Share Code modal like google meet.

### ISSUE THREAD

**Issue by AmeyaJain-25** [kothariji/SyntaxMeets#148]
**Is your feature request related to a problem? Please describe.**
The share code modal can be modified.

**Describe the solution you'd like**
Currently like this.
![Screenshot from 2021-05-30 16-35-23](https://user-images.githubusercontent.com/66305085/120101751-33cf1880-c165-11eb-95c0-7b14b349f1d9.png)
Can be made llike this with feature of adding copy link too.
![Gmeet](https://user-images.githubusercontent.com/60866749/120078247-20bc3a00-c0cc-11eb-95a8-f9c03697d215.png)

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Comment by kothariji** [comment]
Sure @AmeyaJain-25 . Please go ahead. I am assigning this issue to you
