### ISSUE TITLE
Room id hidden

### ISSUE THREAD

**Issue by AmeyaJain-25** [kothariji/SyntaxMeets#150]
**Describe the bug**
Room id is hidden.

**Expected result**
It should be visible complete.

**Actual result**
It got wrapped in ellipsis. And alert also.

**Screenshots**
![Screenshot from 2021-05-31 23-44-05](https://user-images.githubusercontent.com/66305085/120229348-93fbb280-c26a-11eb-98fd-1eebb5465235.png)

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Comment by Akash-Salvi** [comment]
Sure, please go ahead @AmeyaJain-25 , I am assigning this issue to you
