### ISSUE TITLE
Add a leave button to Exit from meet 👋

### ISSUE THREAD

**Issue by kothariji** [kothariji/SyntaxMeets#17]
## Description
Currently, there is no option to leave the meeting. So we just need a `leave meet` button(probably in deep red color)  so that anyone can exit from the meet, and redirect to the home page.

**Comment by Devenkapoor7303** [comment]
Can I work on this issue as a Part of GSSOC 21

**Comment by kothariji** [comment]
> Can I work on this issue as a Part of GSSOC 21

Hi @Devenkapoor7303 , First of all, thank you so much for taking out the time to work on this issue.

Definitely, Please go forward to work on this issue. I am assigning this Issue to you 👍
Few Suggestions from my end:
- button background color deep red.
- leave button should be placed on the rightmost part of the navbar(after about us). It will look nice.
![image](https://user-images.githubusercontent.com/60866749/110289766-e59bf480-800f-11eb-950e-a3c31ac968a8.png)


Also,
Keep Contributing 🙏🔥

**Comment by Devenkapoor7303** [comment]
Okay I will start working on this issue from today onwards ☺️

**Comment by kothariji** [comment]
Sounds Great🔥

**Comment by sahildotexe** [comment]
Hey !! I am a participant of GSSOC'21 , can you assign this issue to me?

**Comment by Akash-Salvi** [comment]
Hey, @sahildotexe, thank you for showing interest 🚀

We appreciate🙏 your dedication and efforts towards our project, but according to our [**contributing guidelines**](https://github.com/kothariji/SyntaxMeets/blob/master/CONTRIBUTING.md), Issues are assigned on the **First Come First Serve** basis.

Anyways feel free to check out other **unassigned issues**, or create an Issue if you spot one🎯.

Thank you😊, and Sorry for the inconvenience caused 🙌

**Comment by Devenkapoor7303** [comment]
@kothariji I have added a leave meeting button can u review it so that i can make a PR?

![Capture](https://user-images.githubusercontent.com/73438023/110446711-51b04400-8074-11eb-93f9-8e6d3d54beee.PNG)

**Comment by kothariji** [comment]
@Devenkapoor7303 This looks really nice, but there is just a slight modification. 

- Can you please just add a start icon, similar to the other buttons like room id, chat box. For eg. you can add **callend** material UI icon 
![image](https://user-images.githubusercontent.com/60866749/110447790-95439600-80e6-11eb-9713-48b3ad3c369a.png)

- Also can you please use this HexCode for the background color of the leave button - #fa1e0e

- Also button text `leave meeting` is kind of **verbose**. So instead you can do with only **Leave** with icon.

**Comment by Devenkapoor7303** [comment]
Okay I will make these changes in the project

**Comment by kothariji** [comment]
> Okay I will make these changes in the project

Sure

**Comment by Devenkapoor7303** [comment]
@kothariji  I have made the changes and added a icon also with the color you have mentioned


![Capture](https://user-images.githubusercontent.com/73438023/110522725-1474a200-80c6-11eb-992c-7504cd740c67.PNG)

**Comment by kothariji** [comment]
Hey @Devenkapoor7303, this looks tremendous.
Please open a PR, so that we can review the code 🙌

**Comment by Devenkapoor7303** [comment]
Okay I will make a PR so that u can review

**Comment by kothariji** [comment]
Fixed 🚀 
Thanks, @Devenkapoor7303 for the contribution 🙌 

Keep Contributing 🔥

**Comment by Devenkapoor7303** [comment]
@kothariji thanks for cooperative nature as u have guided me

**Comment by kothariji** [comment]
> @kothariji thanks for cooperative nature as u have guided me

Thank you 😊 🙏
