### ISSUE TITLE
Displaying list of Participants in Meeting 🧑‍🤝‍🧑🧑‍🤝‍🧑

### ISSUE THREAD

**Issue by kothariji** [kothariji/SyntaxMeets#19]
## Description
Similar to the `chat` side drawer, there should be a `participants list` side drawer, where we can see the list of participants currently in the meeting.

**Comment by murtaza1112** [comment]
Hi , I am interested in resolving in this issue . can I work on this issue as part of GSSOC'21 ?
Discord UserName : murtaza1112#4269

**Comment by kothariji** [comment]
> Hi , I am interested in resolving in this issue . can I work on this issue as part of GSSOC'21 ?
> Discord UserName : murtaza1112#4269

Hi @murtaza1112 , First of all, thank you so much for taking out the time to work on this issue.

Definitely 🙌, Please go forward to work on this issue. I am assigning this Issue to you 👍

Few things I wish to add 📌 
1. Try to add the profile icon(similar to the chat section), so that in the future if a user adds his image, we can display it there. 🖼️ 
2. Also it would be great if you can add roles next to the name of the user, like P - participant, A - admin, so that other participants can know, who is the admin of this meet.(not mandatory). 🧑‍🤝‍🧑 


And last but not least,
Keep Contributing 🙏🔥

**Comment by kothariji** [comment]
Great work @murtaza1112
I really appreciate the way you resolved this issue. 💫
Really a wonderful quality PR's 🙌
Keep up the great work.

Looking forward fpr more contributions from your side 🔥 🙌
