### ISSUE TITLE
Add an Emoji Picker in Chat Drawer🚀🔥😇

### ISSUE THREAD

**Issue by kothariji** [kothariji/SyntaxMeets#24]
## Description
To add an emoji picker tool in the chat drawer so that user can easily send emoji.
Reference
![image](https://user-images.githubusercontent.com/60866749/110218921-55ac5c80-7ee2-11eb-88b0-4ccc85e8e712.png)

**Comment by AishwaryaKaranth** [comment]
Can I work on this issue as part of GSSOC'21 ?

**Comment by kothariji** [comment]
> Can I work on this issue as part of GSSOC'21?

Hi @AishwaryaKaranth, First of all, thank you so much for taking out the time to create this issue.


Yes,  Please go forward to work on this issue. I am assigning this Issue to you 👍

Also, you can take reference from
- https://www.npmjs.com/package/emoji-picker-react
-  https://codesandbox.io/s/m3q0kk1q9j
- https://github.com/missive/emoji-mart
Keep Contributing 🙏🔥

**Comment by AishwaryaKaranth** [comment]
Is there a deadline for resolving this issue?

**Comment by Nishant127** [comment]
Yeah, the deadline is of 1 week as the issue is of Level 2.

**Comment by Priyankcoder** [comment]
@AishwaryaKaranth @kothariji I can work on this issue if you assign it to me.

**Comment by AishwaryaKaranth** [comment]
> @AishwaryaKaranth @kothariji I can work on this issue if you assign it to me.

I am already working on the issue.

**Comment by kothariji** [comment]
Hi, @Priyankcoder, we are assigning this issue to you 🚀
