### ISSUE TITLE
Add a Footer to the application 📃

### ISSUE THREAD

**Issue by kothariji** [kothariji/SyntaxMeets#25]
## Description
A footer should include SyntaxMeets Logo, name(SyntaxMeets), GitHub project link and other stuff.

**Comment by WaderManasi** [comment]
Hi,
I would to contribute on this issue as a part of gssoc'21.

**Comment by kothariji** [comment]
Hi @WaderManasi, First of all, thank you so much for taking out the time to work on this issue.

Definitely, Please go forward to work on this issue. I am assigning this Issue to you 👍

Few things to keep in mind
1. Maintain the color theme used throughout the project. 👉 **[Color Theme]( https://coolors.co/000a29-0077b6-00b4d8-ffd500-f3f7f7-ffffff)** 🎨
2. Need a brand logo and brand name ✅
3. Need an about us page link, and Repo Github page link. 👨 
4. Rest open to endless possibilities. 💯 😊 


Also,
Keep Contributing 🙏🔥

**Comment by Vishv07** [comment]
How about first making Figma/Adobe Xd design for any new design and then write code for it. @kothariji 
It can save much time and will be useful in the future while making new components as well.

**Comment by kothariji** [comment]
@Vishv07 agree with your point. So @WaderManasi we have a basic design prototype and then we can start working on the code part. 
So @WaderManasi can you design a basic layout in Figma/Xd/Canva/Excalidraw so that Once we fix the design, we can work on it. Otherwise directly working on code and then we will do changes.. and then again is some changes are there.. it would be a tedious task.

So it's better If we can finalize the design pattern first.

**Comment by WaderManasi** [comment]
Sure! @kothariji, 
Initially, I will create a basic design prototype mostly in Figma/Canva and will let you know.

**Comment by kothariji** [comment]
> Sure! @kothariji,
> Initially, I will create a basic design prototype mostly in Figma/Canva and will let you know.

Sure 🙌

**Comment by sahildotexe** [comment]
Hey !! I am a participant of GSSOC'21 , can you assign this issue to me?

**Comment by Vishv07** [comment]
> @Vishv07 agree with your point. So @WaderManasi we can have a basic design prototype and then we can start working on the code part.
> So @WaderManasi can you design a basic layout in Figma/Xd/Canva/Excalidraw so that Once we fix the design, we can work on it. Otherwise directly working on code and then we will do changes.. and then again is some changes are there.. it would be a tedious task.
> 
> So it's better If we can finalize the design pattern first.

👍 Great

**Comment by kothariji** [comment]
> Hey !! I am a participant of GSSOC'21 , can you assign this issue to me?

Hey, @sahildotexe, thank you for showing interest 🚀

We appreciate🙏 your dedication and efforts towards our project, but according to our [*contributing guidelines](https://github.com/kothariji/SyntaxMeets/blob/master/CONTRIBUTING.md), Issues are assigned on the **First Come First Serve* basis.

Anyways feel free to check out other *unassigned issues*, or create an Issue if you spot one🎯.

Thank you😊, and Sorry for the inconvenience caused 🙌

**Comment by WaderManasi** [comment]
#### Hi @kothariji, This is basic design layout of footer .If there are any changes kindly let me know so that I can start with actuall coding part.
![syntaxmeets footer (1)](https://user-images.githubusercontent.com/52437677/110620539-1ff7c400-81bf-11eb-8a15-a0b45d0c0ef4.png)

**Comment by WaderManasi** [comment]
Sure !

**Comment by kothariji** [comment]
Great 🚀
Thanks, @WaderManasi for the contribution 🙌

Keep Contributing 🔥
