### ISSUE TITLE
Adding GitHub issue templates

### ISSUE THREAD

**Issue by maneprajakta** [kothariji/SyntaxMeets#27]
Hi :)
Right now there is no issue template for Project.
I think we should take advantage of GitHub’s support for multiple issue templates.

You can see here : 
![64684565-3c595a00-d47d-11e9-8ea4-589cffa16375](https://user-images.githubusercontent.com/57425995/109375319-d6b39480-78e1-11eb-9a72-3c14118cde19.png)

I think right now two templates for creating an issue will do great.
1.For bug report 
2.For feature request

Like this :
![Screenshot from 2021-02-27 09-53-01](https://user-images.githubusercontent.com/57425995/109375368-3f9b0c80-78e2-11eb-88bf-ab9dc5464f3d.png)

**Comment by maneprajakta** [comment]
I would like to contribute to this issue as a part of gssoc 2021.

**Comment by kothariji** [comment]
Hi @maneprajakta, First of all, thank you so much for taking out the time to create this issue.

Sure for now we can have two templates:- 
1.For bug report 🐛 
2.For feature request ⭐ 


Please go forward to add an ISSUE_TEMPLATE to the project.

Also,
Keep Contributing 🙏🔥

**Comment by maneprajakta** [comment]
@kothariji  Sure!

**Comment by kothariji** [comment]
PR #28 fixes this Issue. 👍
