### ISSUE TITLE
Long chat message breaks div 

### ISSUE THREAD

**Issue by Vishv07** [kothariji/SyntaxMeets#30]
When the user types a long message. It simply breaks⚡ down the div and the user cant see the outside part of a message.

![image](https://user-images.githubusercontent.com/37216460/110303530-80043400-8020-11eb-8e20-96d52c55807b.png)

🔨Fixes:

1) can be fixed with minor CSS changes🧨

2) But if you guys planning to change Chat UI/UX then we can wait and can be implemented in the new Design.

**Comment by kothariji** [comment]
Hi @Vishv07, First of all, thank you so much for taking out the time to create this issue🚀 

Great 💯. I was unaware of that Issue. 
As of now, we don't have any plan for changing the UI of the Chat much. 
So I think we can work on this issue.

Please let me know if you wish to work on the same.

**Comment by Vishv07** [comment]
Okay. I'll open the PR by today Itself.

**Comment by Vishv07** [comment]
#33 Opend

**Comment by kothariji** [comment]
@Vishv07 Great 🚀
I am assigning this issue to you 👍
