### ISSUE TITLE
Pop-up alert message on copying room-id.

### ISSUE THREAD

**Issue by Priyankcoder** [kothariji/SyntaxMeets#44]
Hii :wave: @kothariji. On clicking room-id, an alert message appears which disappears on clicking ok otherwise it remains there and freezes the window. I know it is the default behaviour of alert messages but we can do a better UI friendly message alert that fades away on clicking the copy button. It doesn't freeze the windows too and doesn't require any user interaction.

**Comment by Priyankcoder** [comment]
I would like to work on this issue as GSSOC'21 participant.

**Comment by kothariji** [comment]
Hi @Priyankcoder, First of all, thank you so much for taking out the time to create this issue. 🚀 

can you show me a basic design/animation/screenshot or example, if you have one so that it will be more clear to us, what you are aiming to build.

**Comment by Priyankcoder** [comment]
Here is the basic design example [gif](https://imgur.com/a/c43tIuy).

**Comment by kothariji** [comment]
Looks Great, you can go for it. I am assigning this issue to you. 🙌

**Comment by kothariji** [comment]
Thank you for your contributions @AmeyaJain-25 🚀 

Keep Contributing 🙏 🔥

**Comment by kothariji** [comment]
Thank you for your contributions @Priyankcoder  🚀 

Keep Contributing 🙏 🔥
