### ISSUE TITLE
Adding styling to cards of in About Us section

### ISSUE THREAD

**Issue by ankitaugale23** [kothariji/SyntaxMeets#46]
**Is your feature request related to a problem? Please describe.**
Right now, this section looks good but if we add some styling to the cards such as:
1. Card will only show name and bio at the start.
2. After hovering over it it will display all the links and enhancing some more styling in cards so it will highlight the card we are looking at.

**Describe the solution you'd like**

**Motivation**
Please outline the motivation for the proposal.

**Are you willing to contribute to this issue?** [Yes/No]

**Describe alternatives you've considered**

**Additional context**
If you want I can provide you the video of the effect I am talking about.
Please let me know @kothariji @Akash-Salvi @Nishant127

**Comment by kothariji** [comment]
Hi @ankitaugale23, First of all, thank you so much for taking out the time to create this issue.

It would be a great help if you can provide a small video/animation so that we can get a clever idea.

Also please mention in the issue, that would you like to work on this issue😊 

And last but not least,
Keep Contributing 🙏🔥

**Comment by ankitaugale23** [comment]
Sure. I will send it to you by tomorrow.

**Comment by Jimmy5467** [comment]
If you permit me I would like to contribute to this issue.
Suggestion: I will not completely copy as same as that of @ankitaugale23 I will do some modification myself to look it better if you permit.

**Comment by kothariji** [comment]
> Sure. [https://drive.google.com/file/d/15xTBB07m0jH06gjh_E-LShT4B2tVxWjF/view?usp=sharing](url)
> This is a demo to just show what actually my idea we can modify according to your liking but this will just utilize our space.
> @kothariji

@ankitaugale23 this looks really nice, but as there are 3 creators, so how would manage all 3 cards in the same row,(refer pic)
![image](https://user-images.githubusercontent.com/60866749/111139315-ff58b100-85a6-11eb-9a0b-8a363b7d8252.png)

**Comment by Abhishekkr93** [comment]
I would like to contribute as a Gssoc21 participant. could you please assign me this?

**Comment by kothariji** [comment]
any updates @ankitaugale23  ?

**Comment by ankitaugale23** [comment]
> any updates @ankitaugale23 ?

Sorry. I am having my exams right now. Will it be okay with you if I revert back with my idea and changes till 3rd April? After confirmation from your side to the idea about how I will do it for 3 members I will complete the coding part in maximum of two days. Let me know if this is fine with you guys.

**Comment by kothariji** [comment]
> > any updates @ankitaugale23 ?
> 
> Sorry. I am having my exams right now. Will it be okay with you if I revert back with my idea and changes till 3rd April? After confirmation from your side to the idea about how I will do it for 3 members, I will complete the coding part in a maximum of two days. Let me know if this is fine with you guys.

Sure No problem @ankitaugale23, and all the best for the examinations 🚀

**Comment by kothariji** [comment]
Hi @ankitaugale23, any updates ??

**Comment by ankitaugale23** [comment]
I will make a PR till Sunday at 9 pm. Is that fine? And I apologize for being inactive in the communication but I will for sure make my PR this Sunday.

**Comment by kothariji** [comment]
> I will make a PR till Sunday at 9 pm. Is that fine? And I apologize for being inactive in the communication but I will for sure make my PR this Sunday.

No issues @ankitaugale23, but please share a basic design /prototype for the same. So that if there are changes we can do that in early stage, and once we finalized the design, we are good to go for code.

**Comment by ankitaugale23** [comment]
I didn't quite get what should I send you as a prototype/design? (Animation video of the same effects but for these 3 cards) that's what should I send or I am misinterpreting it? Please let me know. @kothariji

**Comment by kothariji** [comment]
> I didn't quite get what should I send you as a prototype/design? (Animation video of the same effects but for these 3 cards) that's what should I send or I am misinterpreting it? Please let me know. @kothariji

Yes,a actually a basic canva design would also work. I just want to see, how final presentation would look like 😊

**Comment by ankitaugale23** [comment]
Sure. I will share it with you today in some time. @kothariji

**Comment by ankitaugale23** [comment]
Here are the canva designs. [https://drive.google.com/drive/folders/1BFSZTZLORMEEqdTBohHp0IdHUt6mDzvI?usp=sharing](url)
Let me know what do you think and if any changes you want. 
One thing I would like to mention is that the cards will be revealed vertically as we don't have much space horizontally.
@kothariji

**Comment by kothariji** [comment]
Hi @ankitaugale23 I saw the design, but somewhere I don't feel that there is a real need for it. 
![image](https://user-images.githubusercontent.com/60866749/115587329-30857900-a2eb-11eb-9d5f-718d92417268.png)

According to UX, only names with big pictures will not look pretty. 
I hope you understand 🙌

**Comment by kothariji** [comment]
> Here are the canva designs. [https://drive.google.com/drive/folders/1BFSZTZLORMEEqdTBohHp0IdHUt6mDzvI?usp=sharing](url)
> Let me know what do you think and if any changes you want.
> One thing I would like to mention is that the cards will be revealed vertically as we don't have much space horizontally.
> @kothariji

#### Hi @ankitaugale23 I saw the design, but somewhere I don't feel that there is a real need for it. 
![image](https://user-images.githubusercontent.com/60866749/115587829-bacddd00-a2eb-11eb-8c41-8d58337bec51.png)

According to UX, only names with big pictures will not look pretty. 
I hope you understand 🙌

**Comment by ankitaugale23** [comment]
I understand. I will work on different issues no problem. 
Thanks for considering my idea though!

**Comment by kothariji** [comment]
> I understand. I will work on different issues no problem.
> Thanks for considering my idea though!

Thank you, sorry for the inconvenience caused 🙌
