### ISSUE TITLE
Enter Key should submit Forms 

### ISSUE THREAD

**Issue by anhushree** [kothariji/SyntaxMeets#50]
**Describe the solution you'd like**
For creating a room or joining a room, after filling in the necessary information, if the user presses Enter Key, it should automatically take us to the result page.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Comment by Nishant127** [comment]
Hi @anhushree, First of all, thank you so much for taking out the time to work on this issue.

Yeah, it would be great if the user can directly enter the room by pressing <kbd>Enter Key</kbd>.
Definitely 🙌, Please go forward to work on this issue. I am assigning this Issue to you 👍

And last but not least,
Keep Contributing 🙏🔥

**Comment by anhushree** [comment]
Thank you so much

**Comment by kothariji** [comment]
any updates @anhushree  ?

**Comment by anhushree** [comment]
```
<MUIButton
    style={{
      marginLeft: "auto",
      marginRight: "auto",
      backgroundColor: "#ffd500",
    }}
    variant="contained"
    size="large"
    component={Link}
    to={{
      pathname: roomId,
      name: name,
    }}
  >
    Create Room
  </MUIButton>
```
On the website when I click on this particular button, it directs me to a page.
Well, I'm unable to find that particular click listener in the code.
Since I'm new to this project, I find it hard to navigate to that part.

**Comment by kothariji** [comment]
> ```
> <MUIButton
>   style={{
>     marginLeft: "auto",
>     marginRight: "auto",
>     backgroundColor: "#ffd500",
>   }}
>   variant="contained"
>   size="large"
>   component={Link}
>   to={{
>     pathname: roomId,
>     name: name,
>   }}
> >
>   Create Room
> </MUIButton>
> ```
> 
> On the website when I click on this particular button, it directs me to a page.
> Well, I'm unable to find that particular click listener in the code.
> Since I'm new to this project, I find it hard to navigate to that part.

I think you can use `onKeyDown` event, and inside that check the key code of the key pressed by user. If Key == enter, then we can make user join the room.

Reference - [Stackoverflow](https://stackoverflow.com/questions/43384039/how-to-get-input-textfield-values-when-enter-key-is-pressed-in-react-js#:~:text=Use%20onKeyDown%20event%2C%20and%20inside,and%20put%20the%20logic%20there.&text=Note%3A%20Replace%20the%20input%20element,define%20the%20other%20properties%20also.&text=Adding%20onKeyPress%20will%20work%20onChange%20in%20Text%20Field.)

**Comment by kothariji** [comment]
any updates @anhushree

**Comment by anhushree** [comment]
@kothariji  I have submitted the PR, kindly check
