### ISSUE TITLE
CORS issue while handling backend requests. 

### ISSUE THREAD

**Issue by Vishv07** [kothariji/SyntaxMeets#51]
**Describe the bug**
CORS get blocked bcz Socket didn't configured by all origins 

**Expected result**
 It should handle backend req.

**Are you willing to contribute to this issue?** [Yes]

**Comment by Vishv07** [comment]
Resolved. Open a PR #47

**Comment by kothariji** [comment]
Great 🙌, Thank you so much fr resolving this issue.
