### ISSUE TITLE
Docs: Change the github command to set the upstream in CONTRIBUTING.md

### ISSUE THREAD

**Issue by KshitijDarekar** [kothariji/SyntaxMeets#54]
**Describe the bug**
There is a minor change required in the GitHub command to set the upstream repository in the Contributing.md file.
The current command gives an error: " fatal: pathspec 'upstream' did not match any files "

**Screenshots**
![image](https://user-images.githubusercontent.com/63798770/111037870-07e8a480-844c-11eb-9855-082b2124e954.png)
![image](https://user-images.githubusercontent.com/63798770/111037951-64e45a80-844c-11eb-86ab-c4d9fcb51630.png)

**Are you willing to contribute to this issue?**
Yes

**Comment by AyushShri** [comment]
Hi @KshitijDarekar , First of all, thank you so much for taking out the time to create this issue #54

I looked through your issue and realized it's a command error.

Definitely:raised_hands:, Please go forward to work on this issue. I am assigning this Issue to you :thumbsup:

And last but not least,
Keep Contributing :pray::fire:

**Comment by KshitijDarekar** [comment]
@AyushShri  I have made a PR #59 .

**Comment by kothariji** [comment]
Thank you for your contributions @KshitijDarekar  🚀 

Keep Contributing 🙏 🔥
