### ISSUE TITLE
[Feat]: Add Option to upload code from local files

### ISSUE THREAD

**Issue by jainaayush01** [kothariji/SyntaxMeets#57]
**Is your feature request related to a problem? Please describe.**
Sometimes a user may have a particular file to modify.

**Describe the solution you'd like**
Add Option to upload code from local files

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Describe alternatives you've considered**
User can add files from local storage for the chosen Language and it should have the same extension for a file to be uploaded
(We can also add upload from google drive as an option).

**Comment by AyushShri** [comment]
Hi @jainaayush01  , First of all, thank you so much for taking out the time to create this issue #57

Currently, the upload from the local feature is not available, Hence as you aforesaid, it would be great if this feature is also added.
For the MVP design of this feature, it would be great if we can add the " Upload from Local Storage " feature first and then continue on from fetching from the Drive feature.
It would be great if after uploading from the local storage, the system detects the extension of the code file and automatically switches to that language for further editing of the code on the platform.

Please go forward to work on this issue.  raised_hands I am assigning this Issue to you +1

And last but not least,
Keep Contributing prayfire

**Comment by jainaayush01** [comment]
Okay sure I will try to implement " Upload from Local Storage " feature first. 
Thanks for your time

**Comment by kothariji** [comment]
> Hi @jainaayush01 , First of all, thank you so much for taking out the time to create this issue #57
> 
> Currently, the upload from the local feature is not available, Hence as you afore-mentioned, it would be great if this feature is also added.
> For the MVP design of this feature, it would be great if we can add the " Upload from Local Storage " feature first and then continue on for fetching from the Drive feature.
> It would be great if after uploading from the local storage, the system detects the extension of the code file and automatically switches to that language for further editing of the code on the platform.
> 
> Please go forward to work on this issue.🙌 I am assigning this Issue to you 👍
> 
> And last but not least,
> Keep Contributing 🙏🔥

True, these points are really impressive. 🙌 
Detecting a file language by its extension and changing the file accordingly would really improve UX.  💫 
Great to go @AyushShri  🚀

**Comment by Nishant127** [comment]
@jainaayush01 any updates?

**Comment by jainaayush01** [comment]
Oh no, I totally forgot about this issue.
Okay,
Where should we provide this option.

**Comment by jainaayush01** [comment]
@Nishant127 I have made the Pull Request. Thanks again for reminding me.
