### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by jainaayush01** [kothariji/SyntaxMeets#58]
**Describe the bug**
Describe the issue that you're seeing clearly.
![image](https://user-images.githubusercontent.com/54480934/111055959-1ca35780-84a1-11eb-843a-955591e1b0f8.png)

**To Reproduce**
Clear steps describing how to reproduce the issue.
1. Go to syntax meet
2. Create a room
3. Scroll Horizontally
4. See Error caused due to footer content

**Expected result**
What should happen?
![image](https://user-images.githubusercontent.com/54480934/111056001-71df6900-84a1-11eb-874a-2b4b2d84fe04.png)

**Actual result**
Extra Margin was added due to footer content.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 89.0.4389.82 (Official Build) (64-bit)

**Additional context**

**Comment by jainaayush01** [comment]
It can be resolved by removing margin-right as shown in expected results(Inspect Tab)

**Comment by Nishant127** [comment]
Hi @jainaayush01, First of all, thank you so much for taking out the time to create this issue.

Definitely 🙌, Please go forward to work on this issue. We are assigning this Issue to you 👍

And last but not least,
Keep Contributing 🙏🔥
