### ISSUE TITLE
Share button for room-Id

### ISSUE THREAD

**Issue by simran2607** [kothariji/SyntaxMeets#60]
**Is your feature request related to a problem? Please describe.**
To share the room-code directly through Whatsapp without copying it and then sharing.

**Describe the solution you'd like**
Adding a share button to share room code.

**Are you willing to contribute to this issue?** [Yes/No]
I would like to contribute towards it.

**Comment by Vishv07** [comment]
This feature seems good but look, this whole platform is collaborative and we are sharing code editor and chat and voices in future as well. so there will no necessary for the share button. 

what's your take on this @kothariji

**Comment by kothariji** [comment]
Hi @simran2607, First of all, thank you so much for taking out the time to create this issue #57

Can you please elaborate, what do you mean by room code -> is it the room-Id, or the code present inside the code editor?

If you are talking about room-Id here is a note 👇 
Currently, SyntaxMeets is not mobile responsive, so it is not possible to create/join a room using mobile devices, hence we cannot share room-ID right now, but Yes, we will work on responsiveness and once the responsiveness is done, we can think of it to share room-id directly in WhatsApp.

And last but not least,
Keep Contributing 🙏🔥

**Comment by simran2607** [comment]
I am talking about room-id. and we can share it using whatsapp web if possible. But if not possible I totally understand.

**Comment by Vishv07** [comment]
Ahh! I thought room code. that's why. This seems doable.

**Comment by kothariji** [comment]
> I am talking about room-id. and we can share it using WhatsApp web if possible. But if not possible I totally understand.

Hey Simran, suddenly an idea 💡 hoped into my mind, instead of limiting it to WhatsApp, It would be better if we can make a generalized message. For eg- currently, when we click on room-Id only room-Id is copied to the clipboard.
But instead of that, we can have a personalized message for Eg.
```
Hi there! You have been invited by Simran to join SyntaxMeets 🚀 

👆Click on this link to join -  https://syntaxmeets.vercel.app/oywZ-AvYl-HJGm
 
Or simply open SyntaxMeets and enter your name and Room-Id: oywZ-AvYl-HJGm
```
So using this personalized message we can send it to any platform.

For Eg. 
![image](https://user-images.githubusercontent.com/60866749/111070763-2658a980-84f9-11eb-99b2-8e18fb199d5e.png)

Share your thoughts @simran2607 @Vishv07

**Comment by simran2607** [comment]
Yes this seems great !!!

**Comment by kothariji** [comment]
> Yes this seems great !!!

Yes, So do let me know If you wish to work for the same 🚩

**Comment by simran2607** [comment]
Yes I would definitely do it

**Comment by kothariji** [comment]
Great, we are assigning this issue to you 🙌

**Comment by simran2607** [comment]
Hey using directly link will require name of the participant and then its been directed to home page. So we can't provide direct link as of now. So shall I work upon this sharing link feature as well ?

**Comment by kothariji** [comment]
> Hey using directly link will require name of the participant and then its been directed to home page. So we can't provide direct link as of now. So shall I work upon this sharing link feature as well ?

Yes, actually for now in the message we can write the steps, like 
Something like that, instead of direct link
```
SyntaxMeets and enter your name and Room-Id: oywZ-AvYl-HJGm
```
