### ISSUE TITLE
SVG not covered on landing Page

### ISSUE THREAD

**Issue by AmeyaJain-25** [kothariji/SyntaxMeets#62]
**Describe the bug**
The svg is not covered fully on home page

**To Reproduce**
Clear steps describing how to reproduce the issue.
1. Go to 'Home page'
3. Scroll down to 'bottom' if 'required'
4. See blank white space not covering the page.

**Expected result**
The svg should cover the whole page and not look half covered.

**Screenshots**
![Screenshot from 2021-03-14 15-38-45](https://user-images.githubusercontent.com/66305085/111065539-5a73a080-84e0-11eb-9e5c-49b741a62316.png)
At the bottom there is the white space which is seen. This is to be removed or covered

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Additional context**
I would like to work on this issue under GSSoC 21'
Though issue is small. It doesn't looks great on the landing page itself.

**Comment by kothariji** [comment]
Hi @AmeyaJain-25, First of all, thank you so much for taking out the time to create this issue.

Yes, it is looking somewhat unpleasent.
Definitely 🙌, Please go forward to work on this issue. We are assigning this Issue to you 👍

And last but not least,
Keep Contributing 🙏🔥

**Comment by kothariji** [comment]
Thank you for your contributions @AmeyaJain-25 🚀 

Keep Contributing 🙏 🔥
