### ISSUE TITLE
Add Close button for closing Chat

### ISSUE THREAD

**Issue by AmeyaJain-25** [kothariji/SyntaxMeets#65]
**Is your feature request related to a problem? Please describe.**
User can close the chat only by clicking in the shaded area. He/She should have an Close icon at top right or top left corner of the chat box to close it.

**Describe the solution you'd like**
I would like to add the close icon button to close the chat box.

**Motivation**
This feature is for better user experience and user friendly.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

Please assign me this issue under GSSoC 21'

**Comment by kothariji** [comment]
Hi @AmeyaJain-25 , First of all, thank you so much for taking out the time to create this issue.

Oh Yeah, we totally forgot that 😅.  
Definitely 🙌, Please go forward to work on this issue. We are assigning this Issue to you 👍

And last but not least,
Keep Contributing 🙏🔥

**Comment by kothariji** [comment]
> **Is your feature request related to a problem? Please describe.**
> User can close the chat only by clicking in the shaded area. He/She should have an Close icon at top right or top left corner of the chat box to close it.
> 
> **Describe the solution you'd like**
> I would like to add the close icon button to close the chat box.
> 
> **Motivation**
> This feature is for better user experience and user friendly.
> 
> **Are you willing to contribute to this issue?** [Yes/No]
> Yes
> 
> Please assign me this issue under GSSoC 21'

Hi @AmeyaJain-25, it would be great if you do the same for the Participants list also 🚀

**Comment by AmeyaJain-25** [comment]
Yes Sure, I'll do it for the Participants list too

**Comment by kothariji** [comment]
> Yes Sure, I'll do it for the Participants list too

Wonderful 🙌
