### ISSUE TITLE
For Chatbox , Add 'user is typing' functionality . 

### ISSUE THREAD

**Issue by murtaza1112** [kothariji/SyntaxMeets#66]
**Is your feature request related to a problem? Please describe.**
In the chatbox , it can't be seen if a user is currently typing a message .

**Describe the solution you'd like**
Show the name of user typing above the submit input above the input tag in the chatbox . 

**Motivation**
A common feature in all chat applications .

**Are you willing to contribute to this issue?** 
Yes

**Comment by kothariji** [comment]
Hi @murtaza1112, great to see you back 🙌.
Thank you so much for taking out time to create this issue 🚀 

Yes, Please go forward to work on this issue, I am assigning this issue to you 🔥.
(Might be a little challenging 😆) I want to see what you can think off, when multiple users are typing at the same time.
Keep Contributing 🙌

**Comment by amaan-ahmad** [comment]
Hey guys @kothariji @murtaza1112, doesn't this issue resembles #35 ?

**Comment by kothariji** [comment]
Excellent work @murtaza1112

Thank you so much for your contributions 🚀

Keep Contributing 🔥

**Comment by kothariji** [comment]
> Hey guys @kothariji @murtaza1112, doesn't this issue resembles #35?

No, @amaan-ahmad, actually issue #35 is based on SyntaxEditor(it will display the name of active user who is typing in syntax Editor), whereas this issue is for ChatBox.
