### ISSUE TITLE
Room ID generation

### ISSUE THREAD

**Issue by Vaibhav-afk** [kothariji/SyntaxMeets#68]
**generateRoomId method inside home.js**

- The room Id generated from this method will be inefficient and less secure, as it is generated from set of lowerCase & upperCase Alphabets. 

**solution**

- We can use `uuid` npm package for generating unique Id's, created from cryptographically-strong random values.

**Screenshots**
![1](https://user-images.githubusercontent.com/67143938/111151657-c542db80-85b5-11eb-9e09-806e529685f7.PNG)

**Comment by kothariji** [comment]
Hi @Vaibhav-afk, First of all, thank you so much for taking out the time to create this issue.

Generally, we thought to make room-Id more user-friendly and in a presentational format. So we came up with a pattern 
**`xxxx-yyyy-zzzz`**. Also, the possible numbers of rooms are 52^12 which is huge.
So I feel, currently, there is not a need for UUID generated room-Ids

What are your thoughts on this @Vaibhav-afk ?

**Comment by Vaibhav-afk** [comment]
Yeah!  you are absolutely right but in case of scaling, it would help.
