### ISSUE TITLE
🚀[Feat]: code and illustrations are lost once you refresh

### ISSUE THREAD

**Issue by simran2607** [kothariji/SyntaxMeets#69]
**Is your feature request related to a problem? Please describe.**

Once you refresh you lose all the code/illustrations and you can't continue from where you left. And you have to join as new member with no old code/illustrations.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Comment by kothariji** [comment]
Hi @simran2607 , great to see you back 🙌.
Thank you so much for taking out time to create this issue 🚀

Yes, Please go forward to work on this issue, I am assigning this issue to you 🔥.

Also localStorage( ) can play a vital role in this. Do check it out 🙌

**Comment by AyushShri** [comment]
Hey @simran2607 , Glad to know you are working on this issue.
It would be really great if you solve this issue.
Also as the issue sounds interesting to me, I would really like to know the implementation methodology that you have in mind for solving this issue. Please let us know the same!
Happy Contributing!

**Comment by simran2607** [comment]
> Hey @simran2607 , Glad to know you are working on this issue.
> It would be really great if you solve this issue.
> Also as the issue sounds interesting to me, I would really like to know the implementation methodology that you have in mind for solving this issue. Please let us know the same!
> Happy Contributing!

Hey there! 
implementation involved : an array at server side which stores all the rooms created. Frontend fetches that array. When user refreshes the page, if the room is present, user is reconnected to its room and code is generated from previous users.

I hope you get it. 
Happy contributing!

**Comment by AyushShri** [comment]
Hey @simran2607 , after quickly going through your strategy, I have few doubts about your methodology-
- Have you implemented any authentication idea for retrieving from the local storage. ( anybody else with the link should not be able to open the code except the one who created or joined the room)
- What's your strategy for storing and retrieving the code data ? (As you might be knowing, data from sockets is lost once you refresh or close it ) 
Rest your idea is good to go for this issue !
Happy Contributing!

**Comment by simran2607** [comment]
If a user join then his name and room-id are stored in his local storage. And if reconnects  his name and room-id will be used to connect him again as a new user. The user won't be redirected to  home page ... And will be connected back . 
In this process, authentication is not needed
