### ISSUE TITLE
🐛 [Bug]: Illustrations are not reflected

### ISSUE THREAD

**Issue by simran2607** [kothariji/SyntaxMeets#70]
**Describe the bug**
Describe the issue that you're seeing clearly.
As you can see in the provided screenshots that codes are being reflected to all members but illustrations are not.

**Expected result**
Illustrations should be visible to all the members.

**Actual result**
Illustration is visible only to the one who drew it.

**Screenshots**

![c2](https://user-images.githubusercontent.com/56145342/111167709-64240380-85c7-11eb-8fac-a0986bf80657.PNG)
![c1](https://user-images.githubusercontent.com/56145342/111167723-65edc700-85c7-11eb-850c-09c9877ec8ae.PNG)

**Are you willing to contribute to this issue?** [Yes/No]
yes

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [e.g. chrome, safari] : chrome
 - Version [e.g. 22] : 89.0.4389.82

**Comment by kothariji** [comment]
Hi @simran2607, First of all, thank you so much for taking out the time to create this issue.

Actually, we are already working on a similar issue #22.

Sorry for the inconvenience caused 🙌 .
Keep contributing 🔥
