### ISSUE TITLE
Default Source code in SyntaxEditor remains unchanged on changing the programming language from the drop-down. 

### ISSUE THREAD

**Issue by amaan-ahmad** [kothariji/SyntaxMeets#71]
**Describe the bug**
Default Source Code in SyntaxEditor doesn't change on changing the language from the drop-down.

**To Reproduce**
Clear steps describing how to reproduce the issue.
1. Create or Join a room by navigating to [Syntaxmeets](https://syntaxmeets.netlify.app/)
2. Try to change the programming language from the SyntaxEditor drop down. for example, change it from C++ to Python.
3. Notice that the default source code doesn't change to python equivalent/similar source code as expected.

**Expected result**
The source code of the default programming language should change to the default source code for the selected programming language.

**Actual result**
The source code in the editor remains unchanged even after changing the programing language from the drop-down in SyntaxEditor.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google chrome
 - Version 89.0.4389.82 (Official Build) (64-bit)

**Additional context**
Default code for languages are recently added, we just need to add default "source code" for each mentioned programming language.

**Comment by kothariji** [comment]
Hi @amaan-ahmad, First of all, thank you so much for taking out the time to create this issue.

We are already working on a similar issue #16.
Sorry for the inconvenience 🙏
