### ISSUE TITLE
Snackbar instead of Javascript alert when copying code using "Copy" button.

### ISSUE THREAD

**Issue by amaan-ahmad** [kothariji/SyntaxMeets#72]
**Is your feature request related to a problem? Please describe.**
This feature request is the enhancement of the existing "copy code" feature.

**Describe the solution you'd like**
On clicking the "Copy" Button in SyntaxEditor a javascript alert pops up saying "Code Copied Sucessfully". This default alert can be enhanced and a [snackbar](https://material.io/components/snackbars) can be used.

**Motivation**
The motive is to enhance UX by replacing old alert with Material design Snackbar.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Describe alternatives you've considered**
Snackbar seems to be a great approach for this feature, but I am open to new suggestions 😊

**Comment by kothariji** [comment]
Hi @amaan-ahmad, First of all, thank you so much for taking out the time to create this issue.

But, we have already fixed this issue with PR #53.
You can check the updated website here - https://syntaxmeets.vercel.app/

Thanks 🙏

**Comment by amaan-ahmad** [comment]
Hey @kothariji 
Yes, you are right about the room ID copy button, but the copy button that copies the "source code" of the code editor is still the former one. Kindly re-check. 


**Screenshot** 
![image](https://user-images.githubusercontent.com/27350808/111275075-c0d0fe00-865b-11eb-9990-c2cb72c2d066.png)

Would be happy to make this small contribution.

Thanks.

**Comment by kothariji** [comment]
@amaan-ahmad Oh.
Sorry for the inconvenience 🙏  caused.I misunderstood the code with Room-id.

Definitely 🙌, Please go forward to work on this issue. We are assigning this Issue to you 👍

And last but not least,
Keep Contributing 🙏🔥

**Comment by amaan-ahmad** [comment]
Hey @kothariji 

I just saw that this issue got assigned to me.

I Will start working on it from tomorrow. ✌
