### ISSUE TITLE
Add Code share feature that generates an image of the Code Snippet.

### ISSUE THREAD

**Issue by AyushShri** [kothariji/SyntaxMeets#74]
- The idea is to add a Share button that generates a link of the code snippet converted in some beautified form. [(see ref. example)](https://carbon.now.sh/JrHP5h3gCy3uyVz38lOQ)
- This Link would be sharable to different users with the READ ONLY and ctrl+c  access.
- We can use an external API Service for this. Example: [Carbon.sh](https://carbon.now.sh/).
- If implementing on our own, then the sharable data must be dumped after say 12 Hours and hence the link would be valid for 12 Hours only. 

#GSSOC21

**Comment by bishalshaw-164** [comment]
I'm gssoc'21 participant .
I want to work on this issue,
Can you assign issue to me ?

**Comment by AyushShri** [comment]
Hi @bishalshaw-164 , First of all, thank you so much for taking out the time to work on this issue.
Definitely:raised_hands:, Please go forward to work on this issue. I am assigning this Issue to you :thumbsup:

Also for my interest, I would like to know the implementation methodology that you might derive to solve this issue before raising a PR. I'll be delighted to learn about your working approach. 
Happy Contributing! :thumbsup:

**Comment by bishalshaw-164** [comment]
Thanks for asking, I want to use toDataURL() method of HTMLCanvasElement
which returns an encoded data URI representing the image in the specified
format. But now it seems like this issue can't solve by this method.....How
can use carbon.sh. API for this issue Can u pls elaborate??

**Comment by AyushShri** [comment]
Hi @bishalshaw-164, I was not able to keep up with the reply as I was stuck in some work. 
Yes, toDataUrL would not be able to solve this because of Canvas restrictions. Also carbon.sh has no API and works only by Embedding Code or just by typing it. So after having a discussion with @kothariji , we came to the conclusion that we can use PasteBin API for the same. ( as of now we are dropping the idea of exporting as an image). Hence you can go ahead and implement the sharing feature with Pastebin. Rest all functionalities will work as discussed earlier in this issue.
Later we might shift from PasteBin API to Github Gists once the Oauth gets implemented.
For any queries, Feel free to comment.
Happy Contributing!

**Comment by kothariji** [comment]
Hi @bishalshaw-164, any updates ??

**Comment by AyushShri** [comment]
> @kothariji please assign this to me then

 Thanks for coming forward to solve this issue. Please go forward to work on it.

Also for my interest, I would like to know the implementation methodology that you might derive to solve this issue before raising a PR. I'll be delighted to learn about your working approach.
Happy Contributing!

**Comment by subhangi2731** [comment]
@kothariji Access to fetch at 'https://pastebin.com/login' from origin 'http://localhost:3000/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled. 

please reply and help me what should I do
