### ISSUE TITLE
Improve security of website - gssoc'21

### ISSUE THREAD

**Issue by krishna-y2000** [kothariji/SyntaxMeets#75]
**Is your feature request related to a problem? Please describe.**

Setting various HTTP headers using helmet for enhancing security .
Rate limiter so the server won't get overload.

Please assign this issue to me as part of gssoc'21.

**Motivation**
 Improve security of website

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Comment by kothariji** [comment]
Hi @krishna-y2000 , First of all, thank you so much for taking out the time to create this issue.

Before going forward with this issue, can you please explain briefly, how will you achieve rate limiters.
Also, it would be great if you can mention some of the benefits of setting HTTP headers.


And last but not least,
Keep Contributing 🙏🔥

**Comment by krishna-y2000** [comment]
@kothariji Yes, Sure . 
Rate limiter helps to control the the no. of request by user in certain amount of time therby reducing the traffic of the website and thus everyone can handle the site faster. 

Helmet is used to set various http headers and http headers can leak sensitive information. It also protects from clickjacking attack.

**Comment by kothariji** [comment]
> @kothariji Yes, Sure .
> Rate limiter helps to control the the no. of request by user in certain amount of time therby reducing the traffic of the website and thus everyone can handle the site faster.
> 
> Helmet is used to set various http headers and http headers can leak sensitive information. It also protects from clickjacking attack.

Alright, you are good to go. I am assigning this issue to you 🙌
