### ISSUE TITLE
Warnings concerned about web a11y, performance , and security issues. 

### ISSUE THREAD

**Issue by amaan-ahmad** [kothariji/SyntaxMeets#76]
**Describe the bug**
We developers many times don't take warnings seriously, but they are caused for some reasons and some of them are mentioned below.

**To Reproduce**
Clear steps describing how to reproduce the issue.
1. Install all the dependencies and start the react-scripts in the front-end.
2. It takes a while to compile and then you see a lot of warnings about unused variables and a11y issues.

**Expected result**
The server should start successfully without warnings.

**Actual result**
Many warnings flooded for genuine reasons.

**Screenshots**
![image](https://user-images.githubusercontent.com/27350808/111279325-9766a100-8660-11eb-907c-fdd2a2bd4bc1.png)

**Are you willing to contribute to this issue?** [Yes/No]
Yes, I am willing to contribute to this issue.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Node version: 12.13.0

**Additional context**
Explaining why to care about these warning:

- `no-unused-vars` warns about the unused variables that just add up to compile-time memory and causes delay in compilation.
- `jsx-a11y/alt-text` warns about the absence of alternative text on images which is a bad UX and a11y.
- `react/jsx-no-target-blank` warns about the security risk. [Know more](https://mathiasbynens.github.io/rel-noopener/)
- also some dependencies are missing from react `useEffect()` hook causing `react-hooks/exhaustive-deps` 

Regards,
Amaan Ahmad

**Comment by Vishv07** [comment]
It's always better to remove warnings.🔨

**Comment by amaan-ahmad** [comment]
@Vishv07 Yes. right.

**Comment by kothariji** [comment]
Hi @amaan-ahmad , First of all, thank you so much for taking out the time to create this issue.

Thank you for spotting them out
Definitely 🙌, Please go forward to work on this issue. We are assigning this Issue to you 👍

And last but not least,
Keep Contributing 🙏🔥

**Comment by kothariji** [comment]
But, the missing useEffect dependencies are intentionally not added as adding those will call useEffect unwantedly. So handle those warnings wisely 🚀

**Comment by amaan-ahmad** [comment]
Thanks for assigning the issue to me, and I'll take care of that useEffect thing 😊
