### ISSUE TITLE
Making chatbox messages more readable (UI - enhancement)

### ISSUE THREAD

**Issue by amaan-ahmad** [kothariji/SyntaxMeets#80]
**Is your feature request related to a problem? Please describe.**

Problem: In the chatbox, it's challenging sometimes to differentiate between my message and the other person's message as both have the same message box color - rgb(0, 180, 216). (cyan-blue kinda color)
We see most of the chat applications having a contrast of message box color so that it is easier to differentiate between my message and other participant's message.

**Describe the solution you'd like**
Solution: Let's have a different color of message box of my message in the chat section, so that it get's easier for the user to differentiate between my messages and other participant's messages.

**Motivation**
Many chat applications like Whatsapp, telegram, messenger, etc. follow this UX principle.

**Are you willing to contribute to this issue?** [Yes/No]
Yes, I am willing to contribute to this issue.

**Describe alternatives you've considered**
Open to suggestions ✌

**Additional context**
See this screenshot: 

### Better readability:

![image](https://user-images.githubusercontent.com/27350808/111423429-529d4180-8716-11eb-9b1b-87eb8cca8071.png)

**Comment by lakshita15** [comment]
I'am gssoc participant 
I would like to work on this issue. I will submit before due date with fantastic work.

**Comment by Nishant127** [comment]
Hi @amaan-ahmad, Thank you so much for taking out time to create this issue 🚀

Yes, Please go forward to work on this issue, I am assigning this issue to you 🔥.

**(Might be a little challenging)** Only for the user who is sending the message, we want to interchange the positions of Avatar and the message box when he will post his message.
eg: 👇
![image](https://user-images.githubusercontent.com/60032250/111438656-85513500-872a-11eb-8f47-0df166158422.png)


Keep Contributing 🙌

**Comment by Nishant127** [comment]
Hey, @lakshita15  thank you for showing interest 🚀

We appreciate🙏 your dedication and efforts towards our project, but according to our contributing guidelines, Issues are assigned on the First Come First Serve basis.

Thank you😊, and Sorry for the inconvenience caused 🙌

**Comment by Vishv07** [comment]
@lakshita15  before you get into the code part please share Figma/XD design like what exactly you are going to plan.

**Comment by amaan-ahmad** [comment]
Hey @Nishant127 , I'll try this one changing the position. Hopefully will succeed in this✌ 
Kindly assign this issue to me.

Thanks.

**Comment by amaan-ahmad** [comment]
@Nishant127 
Have a look, I did it!

Actually, I stored the name of user in local storage whenever they create/join the room. 
and then compare it with `data.name` in ChatMessage.js as needed to do CSS-in-JS styling. 
Pretty easy. ✌

![image](https://user-images.githubusercontent.com/27350808/111478637-446f1580-8756-11eb-89c0-9bdd10904bb0.png)

**Comment by amaan-ahmad** [comment]
@Nishant127 

As discussed, I have created PR #82 for this issue. 
Kindly add the GSSOC21 label to this issue and assign it to me. 

Thanks 😊

**Comment by Nishant127** [comment]
@amaan-ahmad Well done bro 🚀🔥. 
I have assigned you the issue. You can go ahead now.

**Comment by kothariji** [comment]
## Great Work 🚀 
![image](https://user-images.githubusercontent.com/60866749/111596218-ed6b4e00-87f2-11eb-86c7-97ac3b59c525.png)

Thank you for Contributing 🙌 
Thanks 🔥
