### ISSUE TITLE
Add hover effects and bubble transition to home page buttons..

### ISSUE THREAD

**Issue by lakshita15** [kothariji/SyntaxMeets#81]
I would like to make changes to the buttons on home page. Add hover effects and transitions.
I would  like to add footer section if you insist to the home page.
Please assign me this issue.

**Comment by Akash-Salvi** [comment]
Hey, @lakshita15, thank you for showing interest 🚀

We appreciate🙏 your dedication and efforts towards our project, but we are already working on a similar thing at issue #49. 
Once that issue is resolved, we can work on this issue.

Anyways feel free to check out other unassigned issues, or create an Issue if you spot one🎯.

Thank you😊, and Sorry for the inconvenience caused 🙌

**Comment by simranbhalla3** [comment]
Hi i am a gssoc participant , can i work on this issue? I can add transitions

**Comment by kothariji** [comment]
> Hi i am a gssoc participant , can i work on this issue? I can add transitions

Sorry @simranbhalla3, but this issue is already on hold.

**Comment by Nishant127** [comment]
Hi @lakshita15, we are done with the refactoring of the code. So now you can work on this issue 🙌.
Before going towards the implementation, please can you send basic prototype/design of the same so that we can see the changes.

**Comment by lakshita15** [comment]
I’ll in a day or two

**Comment by lakshita15** [comment]
Please assign the labels for the level

**Comment by kothariji** [comment]
> Please assign the labels for the level

Done, please share a basic animation design/prototype for the same

**Comment by lakshita15** [comment]
https://codepen.io/ritchiejacobs/pen/qEJjBM
https://codepen.io/hilwat/pen/BeemVX
https://codepen.io/davidicus/pen/emgQKJ
Plss have a look at these and tell which one you'd like to have

**Comment by subhangi2731** [comment]
please assign me this I will make a pr by today

**Comment by Furquan712** [comment]
I would like to work on this, will you assign me?

**Comment by kothariji** [comment]
@lakshita15, we really appreciate your dedication and hard work towards our project, but somehow we don't feel like currently there is a need to add a hover effect over the buttons, as the current look is much minimalist and decent. 

Sorry for the inconvenience caused.
