### ISSUE TITLE
Add Dark mode and night light mode

### ISSUE THREAD

**Issue by parulsurana** [kothariji/SyntaxMeets#84]
The dark mode is now everywhere so I would like to enable the dark mode and night light mode to the site so that the site becomes more user friendly and implementing night light mode will not harm much to the eyes of the viewer,  so kindly assign this task to me as I have been selected as a mentee in GSSOC'21 :)

**Comment by kothariji** [comment]
Hi @parulsurana, First of all, thank you so much for taking out the time to create this issue 🚀 

Yeah Even I am a dark node fan, but I would love to see the color combination you are thinking to implement so that we can see how it will look like 🙌

**Comment by parulsurana** [comment]
Okay I will send the color combination design for the same, soon!

**Comment by kothariji** [comment]
any updates @parulsurana  ?

**Comment by parulsurana** [comment]
Hey, @kothariji here I added the snapshots for the design after adding dark mode. I made this using Photoshop for now.

![d](https://user-images.githubusercontent.com/63437071/113023171-fff66780-91a2-11eb-8f09-625bdcc61bd5.PNG)
![d2](https://user-images.githubusercontent.com/63437071/113023156-fc62e080-91a2-11eb-91b7-6e1913be70e3.PNG)
![dd](https://user-images.githubusercontent.com/63437071/113023149-fb31b380-91a2-11eb-8bda-c4b1aea096e8.PNG)
![d3](https://user-images.githubusercontent.com/63437071/113023144-f8cf5980-91a2-11eb-9681-3d7096cecc3f.png)

Here I use the color code #161618 for the background and #161822 for that blue color part.
Please review this and if any changes you want to suggest.

**Comment by Vishv07** [comment]
@parulsurana good one. But can be done better

**Comment by parulsurana** [comment]
Okay, @Vishv07 Can you please suggest something, like I need to change the color I use or to change the color of other components too or anything?

**Comment by kothariji** [comment]
@parulsurana yes there are nice, but honestly, it's not looking that great, even I tried creating a dark theme, but it's not looking good. And I think the reason begins that is colors. Because already we have dark colors in our color palette so inverting those doesn't make much sense. 
Share you opinions, what do you feel regarding the same, and let me know how we can proceed further

![image](https://user-images.githubusercontent.com/60866749/113092380-82b30d00-920b-11eb-8609-5c25c68cd133.png)

**Comment by parulsurana** [comment]
Yeah truly speaking it is not given that great look, because already the dark color was used here.
 One thing we can try is that we can change the color of the button components and that blue one too, like make them something which gone with the dark theme, maybe it looks good, otherwise, we can drop the idea. What say?

**Comment by kothariji** [comment]
Yes even I think the same. Already there are different themes when it comes to coding.
So as of now, I think we should drop this idea, and maybe in the future if you feel like adding anything to this issue, you can reopen it.

Again we all really appreciate your dedication and interest for the project.
