### ISSUE TITLE
Integrating an online compiler to run the code in c , c ++ , java and various languages

### ISSUE THREAD

**Issue by rohitsigar** [kothariji/SyntaxMeets#85]
As I am selected as a mentee in Gssoc'21 so please assign this task to me.
![Screenshot (875)](https://user-images.githubusercontent.com/56029541/111521909-b445c600-877f-11eb-99ef-b71e49f60b36.png)
after a complete walkthrough of the website and source code, I found that there is an error in the compilation of code so  I would love to Integrate the online compiler to run the code, so please assign this issue to me.

**Comment by kothariji** [comment]
Hi @rohitsigar, First of all, thank you so much for taking out the time to create this issue 🚀 

I think you have not set up the environment variables for the project, that why it's showing an error. 
It is working on the deployed version - https://syntaxmeets.vercel.app/

You can set up your online judge API key
## Create a new .env file and add the following variables
```
REACT_APP_SYNTAXMEETS_BACKEND_API = 'http://localhost:4000/'
REACT_APP_ONLINE_JUDGE_API = YOUR API KEY
```
Happy Contributing! 👍
