### ISSUE TITLE
[Feat]: Fullscreen support for code editor.

### ISSUE THREAD

**Issue by amaan-ahmad** [kothariji/SyntaxMeets#87]
**Is your feature request related to a problem? Please describe.**
A feature that could simply allow users to make their code editor window fullscreen.

**Describe the solution you'd like**
I tried ways around "ace editor" which's the current editor dependency we are using in this project. Maybe someone can suggest a way to achieve this. I think it will be worth it if we need to change the Code editor or make "ace editor" work in fullscreen by altering CSS for fullscreen mode.

**Motivation**
Many coding websites including leetcode, hackerrank, geeksforgeeks, etc. do have this essential feature.

**Are you willing to contribute to this issue?** [Yes/No]
Yes, I would be happy to make this work.

**Describe alternatives you've considered**
IMO, Following approaches can be considered:
- make CSS alterations specifically for Fullscreen mode..
- replace ace-editor with some other editor that already supports fullscreen functionality.
- [your suggestion]

**Additional context**
I really don't know how to achieve this as of now, but I can try figuring it out. Also, I am open to suggestions as usual. 🙌

**Comment by kothariji** [comment]
Hi @amaan-ahmad, First of all, thank you so much for taking out the time to create this issue 🚀


I think changing the editor now won't be a good decision, because ace editor provides us with a lot of themes, language support, and reliability. So to achieve full-screen instead of changing editor, we can use some other npm packages like [react-resizable(https://www.npmjs.com/package/react-resizable) or any other.

**Comment by amaan-ahmad** [comment]
Hey @kothariji 
Yes, I too think that changing the editor library at the moment is not a correct decision to follow. Will try to do it in another way.

**Comment by kothariji** [comment]
> Hey @kothariji
> Yes, I too think that changing the editor library at the moment is not a correct decision to follow. Will try to do it in another way.

Sure. 🙌

**Comment by amaan-ahmad** [comment]
Hey @kothariji 

Without changing the editor library, we can implement fullscreen code mode using some CSS alterations like this 👇

![image](https://user-images.githubusercontent.com/27350808/112717707-6dd92f80-8f14-11eb-8af3-dd27814175d4.png)

Kindly let me know if I should go forward with this implementation or not. ✌
(Open to suggestions)

**Comment by kothariji** [comment]
> Hey @kothariji
> 
> Without changing the editor library, we can implement fullscreen code mode using some CSS alterations like this 👇
> 
> ![image](https://user-images.githubusercontent.com/27350808/112717707-6dd92f80-8f14-11eb-8af3-dd27814175d4.png)
> 
> Kindly let me know if I should go forward with this implementation or not. ✌
> (Open to suggestions)

Hey @amaan-ahmad , this looks cool, but what if I want to access the syntax pad, or change the language, or compile the code, how can I do that. Also, what will be the layout design for the same?

**Comment by amaan-ahmad** [comment]
there will be a toggle fullscreen icon button in the bottom right corner that will allow users to exit fullscreen and do their stuff. Do you have an alternate suggestion to this?

**Comment by kothariji** [comment]
> there will be a toggle fullscreen icon button in the bottom right corner that will allow users to exit fullscreen and do their stuff. Do you have an alternate suggestion to this?

How about this thing, instead of making it 100% we can increase the width so that code editor feels big. Just like vscode
![Untitled design (7)](https://user-images.githubusercontent.com/60866749/112938769-e247e480-9147-11eb-8bf0-ba7c99cbfe2a.png)

**Comment by amaan-ahmad** [comment]
okay, does that means it has to get the editor kinda big and hide syntaxpad?

**Comment by kothariji** [comment]
> okay, does that means it has to get the editor kinda big and hide syntaxpad?

No, actually there would be a toggle button on the right side of SyntaxEditor Footer. So on click, it will toggle its size. 
We can name it as *Focus Mode*

**Comment by amaan-ahmad** [comment]
Okay will implement this, and as there were some ongoing updates in the project such as redux and refactoring. So should I proceed with this issue, or hold till the updates get done?

**Comment by kothariji** [comment]
Yes, actually we are working on Refactoring. So once that thing is done, we will let you know, so that you can start working o n the issue. 🙌

**Comment by amaan-ahmad** [comment]
Okay great, I'll wait for it. If possible, kindly do inform/or make an announcement.

Thanks. ✌

**Comment by kothariji** [comment]
> Okay great, I'll wait for it. If possible, kindly do inform/or make an announcement.
> 
> Thanks. ✌

Sure, we will inform you about the same. ✌️

**Comment by kothariji** [comment]
HI @amaan-ahmad, we are done with refactoring the code, so now we are good to work on this issue.

**Comment by amaan-ahmad** [comment]
Okay, @kothariji kindly assign the issue to me.

Thanks.

**Comment by Akash-Salvi** [comment]
Hi @amaan-ahmad, Please go forward to work on this issue. I am assigning this Issue to you 👍

**Comment by amaan-ahmad** [comment]
Thanks @Akash-Salvi , kindly also add a Level tag to this issue.

**Comment by amaan-ahmad** [comment]
hey, guys, @kothariji @Akash-Salvi 
I need a suggestion about where to keep the toggle button for focus mode?
