### ISSUE TITLE
Implementing the participant button

### ISSUE THREAD

**Issue by kotwani2883** [kothariji/SyntaxMeets#90]
**Is your feature request related to a problem? Please describe.**
Whenever the user clicks on participants button the list of currently online participants must be visible.

**Describe the solution you'd like**
To display the participants

**Are you willing to contribute to this issue?** 
Yes

**Comment by kothariji** [comment]
Hi @kotwani2883, First of all, thank you so much for taking out the time to create this issue 🚀

Actually, we have already implemented the Participant Button in our latest release - http://syntaxmeets.vercel.app/

**Comment by kotwani2883** [comment]
Ok great!!
