### ISSUE TITLE
Bug with copying RoomId

### ISSUE THREAD

**Issue by Lavcodes** [kothariji/SyntaxMeets#93]
**Describe the bug**
When you copy the RoomId , the notification is 'RoomId copied'. this is what gets copied. 
Hi there! You have been invited by sanjali to join SyntaxMeets.    Click on this link - https://syntaxmeets.vercel.app    and join the room by providing your name and Room-Id: FsqZ-NjYl-PVGa. 

**To Reproduce**
Clear steps describing how to reproduce the issue.
Create a Room and click on RoomId.

**Expected result**
It would be clearer if the notification said "Invite created! Share with your friends." I believe it is a tiny change but it did confuse me a little when I tried to directly paste this into another window's JOIN ROOM as I thought it had just copied the actual room-id( FsqZ-NjYl-PVGa) 

**Actual result**
Hi there! You have been invited by sanjali to join SyntaxMeets.    Click on this link - https://syntaxmeets.vercel.app    and join the room by providing your name and Room-Id: FsqZ-NjYl-PVGa. 

**Screenshots**

**Are you willing to contribute to this issue?** Yes

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kothariji** [comment]
Hi @Lavcodes, First of all, thank you so much for taking out the time to create this issue.

Definitely 🙌, Please go forward to work on this issue. I am assigning this Issue to you 👍

And last but not least,
Keep Contributing 🙏🔥

**Comment by Lavcodes** [comment]
I've submitted a PR for this
