### ISSUE TITLE
🚀 [FEAT: ] Download code feature.

### ISSUE THREAD

**Issue by amaan-ahmad** [kothariji/SyntaxMeets#96]
**Is your feature request related to a problem? Please describe.**
Downloading the present code editor's code can help developers to keep a local copy of their coding session with them!

**Describe the solution you'd like**
We can easily some libraries to write textarea (code-editor) content to a file and offer it to download.
Refer to [FileSaver.js](https://github.com/koffsyrup/FileSaver.js)

**Motivation**
Numerous online-IDE and coding playgrounds do offer this feature.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Describe alternatives you've considered**
There can be different approaches to the solution to this problem, and I am open to all suggestions.

**Comment by Akash-Salvi** [comment]
Hi @amaan-ahmad, First of all, thank you so much for taking out the time to create this issue. 🚀

We are currently refactoring the entire project code, so once it done we will definitely look forward to this issue.

**Comment by amaan-ahmad** [comment]
Okay, @Akash-Salvi will wait for it. ✌

**Comment by amaan-ahmad** [comment]
hey @Akash-Salvi is it good to go now?

**Comment by kothariji** [comment]
HI @amaan-ahmad, we are done with refactoring the code, so now we are good to work on this issue.

**Comment by AmeyaJain-25** [comment]
If this issue is not taken by anyone or not able to do this, then i wish to take this.
Can I get it?

**Comment by amaan-ahmad** [comment]
hey @AmeyaJain-25 

Thanks for asking, but I am already on this issue, may be got unassigned accidently. @kothariji can you just re-assign it?

**Comment by kothariji** [comment]
Sure

> If this issue is not taken by anyone or not able to do this, then i wish to take this.
> Can I get it?

Sorry @AmeyaJain-25 , we have already in touch with @amaan-ahmad for this issue. 🙏

**Comment by kothariji** [comment]
> hey @AmeyaJain-25
> 
> Thanks for asking, but I am already on this issue, may be got unassigned accidently. @kothariji can you just re-assign it?

Done 🚀

**Comment by amaan-ahmad** [comment]
Thanks @kothariji 

See you in the PR thread soon. ✌

**Comment by amaan-ahmad** [comment]
@kothariji  is there any already built function that returns the extension for the selected language? 
Asking because I was about to make one for the download feature need, so I just thought once I should ask before reinventing things.

**Comment by amaan-ahmad** [comment]
@kothariji NVM, I created a utility function to get extension name by language code. and successfully implemented this feature. doing a PR shortly.

**Comment by kothariji** [comment]
> @kothariji NVM, I created a utility function to get extension name by language code. and successfully implemented this feature. doing a PR shortly.

Great @amaan-ahmad , we will try to review the PR asap.
